server:
  port: 8080
  servlet:
    context-path: /pay-api
  error:
    include-message: always

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.paykernelfun: debug
spring:
  profiles:
    active: dev
